### PR TITLE
Added support for 1.15.X

### LINKED ISSUE #12: Support for 1.15.1
Is it possible to upload a JAR supporting version 1.15.1? I saw the github code got updated but I didn't find a created jar.

### PR DESCRIPTION
**Pull request by ShayPunter**
Added support for 1.15.X, also built using Java 8

### CODE REVIEW

**Review by SpraxDev — APPROVED** [review]
Looks good

**Comment by DrkMatr1984** [comment]
Can u shoot me a jar? Pleaaaaassse? :smile:

**Comment by ShayPunter** [comment]
@DrkMatr1984 for this time certainly, once it has been officially updated on Spigot I would recommend downloading from there to apply any further changes that the author and maintainers of this plugin may have implemented and to also get support for it.

[BetterChairs.zip](https://github.com/BlackScarx/BetterChairs/files/3992310/BetterChairs.zip)

**Comment by BlackScarx** [comment]
I'm at hospital at this time. I come back when I can 😉

**Comment by DrkMatr1984** [comment]
Thanks! I hope you get better @BlackScarx ! I tried to compile from your source myself but I got compiling errors. Thanks for the jar!

**Comment by Ergenta** [comment]
thanks shay

**Comment by makcuber** [comment]
Got this up and running in 1.15.2 with no issues so far, thanks! :)

**Pull request merged**
