### PR TITLE
Various fixes to work with 1.15.X

### LINKED ISSUE #12: Support for 1.15.1
Is it possible to upload a JAR supporting version 1.15.1? I saw the github code got updated but I didn't find a created jar.

### PR DESCRIPTION
**Pull request by hcshires**
I wasn't initially able to find a working jar for BetterChairs for 1.15.2 so I attempted to build one myself via cloning the repository. I noticed a number of issues and have fixed them below. Most importantly, I noticed the spigot jar to implement 1.15_R1 wasn't recognized as a library so I added it to resolve undefined library imports. Additional changes are below:

- Added the spigot-1.15.2.jar to fix undefined library imports
- Changed missing enum reference to PRISMARINE instead of PRISMARINE_BRICK_SLAB to avoid errors (this may need further review)
- Fixed various warnings and redundancies
- Verified the 1.15 build works on my server

### CODE REVIEW

**Comment by SirAltF4** [comment]
what do I do to get this to work? do i just need the 1.15.2 jar and the normal jar?

**Comment by hcshires** [comment]
> what do I do to get this to work? do i just need the 1.15.2 jar and the normal jar?

Are you referring to my pull request or how to get it on your server?

**Comment by SirAltF4** [comment]
How to get it into the server

**Comment by hcshires** [comment]
Make sure to ask in issues next time but I manually created a jar using an IDE, however, BlackScarx provided one for 1.15.x in a different thread: https://github.com/BlackScarx/BetterChairs/files/3992310/BetterChairs.zip

**Comment by SirAltF4** [comment]
I thank you

**Comment by hcshires** [comment]
No problem

**Comment by lusqua** [comment]
I waited so long for this .jar file, that God bless her wonderful being

**Comment by hcshires** [comment]
XD. Unless you have a pull request comment, view the "Jar 1.15" issue in Issues

**Pull request closed without merging**
